# Generated by Django 4.2.4 on 2023-08-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='mail',
            new_name='email',
        ),
    ]
