# Generated by Django 4.2.4 on 2023-08-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_rename_mail_client_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='mail',
        ),
    ]
