# Generated by Django 4.2.4 on 2023-08-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_rename_email_client_mail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mailinglist',
            unique_together={('mailing', 'message', 'client')},
        ),
    ]
