# Generated by Django 4.2.4 on 2023-08-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailingmodel_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmodel',
            name='week_day',
            field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1, null=True, verbose_name='день недели'),
        ),
    ]
