# Generated by Django 4.2.4 on 2023-08-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailingmodel_week_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loglist',
            options={'ordering': ['-time'], 'verbose_name': 'ошибка рассылки', 'verbose_name_plural': 'ошибки рассылки'},
        ),
    ]
