# Generated by Django 4.2.4 on 2023-08-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_loglist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmodel',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.message', verbose_name='текст рассылки'),
        ),
        migrations.AlterUniqueTogether(
            name='mailinglist',
            unique_together={('mailing', 'client')},
        ),
        migrations.RemoveField(
            model_name='mailinglist',
            name='message',
        ),
    ]
