# Generated by Django 4.2.4 on 2023-08-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_mailingmodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=30, verbose_name='название'),
        ),
    ]
