# Generated by Django 4.2.4 on 2023-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='тема письма'),
        ),
    ]
