# Generated by Django 4.2.4 on 2023-08-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='loglist',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingmodel', verbose_name='рассылка'),
        ),
    ]
