# Generated by Django 4.2.4 on 2023-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_loglist_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmodel',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='рассылка проведена'),
        ),
    ]
