# Generated by Django 4.2.4 on 2023-08-04 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_mailingmodel_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время ошибки'),
        ),
    ]
