# Generated by Django 4.2.4 on 2023-08-04 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_alter_loglist_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loglist',
            options={'ordering': ['-time'], 'verbose_name': 'лог рассылки', 'verbose_name_plural': 'логи рассылки'},
        ),
        migrations.AlterField(
            model_name='loglist',
            name='error_message',
            field=models.TextField(verbose_name='успех / сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='error_type',
            field=models.CharField(max_length=50, verbose_name='успех / тип ошибки'),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время рассылки'),
        ),
    ]
