# Generated by Django 4.2.4 on 2023-08-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0015_alter_loglist_options_alter_loglist_error_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loglist',
            old_name='mailing',
            new_name='mailing_model',
        ),
        migrations.RenameField(
            model_name='mailinglist',
            old_name='mailing',
            new_name='mailing_model',
        ),
        migrations.AlterUniqueTogether(
            name='mailinglist',
            unique_together={('mailing_model', 'client')},
        ),
    ]
